//I will use class based data model (available at run time too) rather than interface based data model (available only at compile time and not at run time). Do remember to use public infront of the data types. 
export class Section {
  constructor(
  public id: string,    //id will be generated by Firestore database
  public title: string,
  public type: string,
  public marks: number, 
  public penalty: number,
  public time: number
  ) {}
}