//I will use class based data model (available at run time too) rather than interface based data model (available only at compile time and not at run time). Do remember to use public infront of the data types. 
export class TestPackage {
  constructor(
  public id: string,    //id will be generated by Firestore database
  public title: string, 
  public price: number,
  public startDate: string,
  public endDate: string,
  public description?: string, //description may be an empty string
  ) {}
}